--drop table atividade;
--drop table participante;
--drop table evento;

CREATE TABLE PARTICIPANTE (
    PARTICIPANTECOD INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    SENHA VARCHAR(255),
    TAMANHOCALCA INTEGER,
    TAMANHOCAMISA INTEGER,
    TAMANHOSAPATO INTEGER,
    INTERESSES VARCHAR(255),
    PRIMARY KEY (PARTICIPANTECOD)
);

INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Cecilia','Mauris.blandit@lacusEtiambibendum.org','Henry',35,39,46,'viverra. Donec tempus, lorem');
INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Fuller','ullamcorper.nisl@erosNam.co.uk','Jasper',49,36,39,'nec, diam. Duis mi');
INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Germane','hendrerit@Mauris.com','Rogan',45,40,43,'sapien. Aenean massa. Integer');
INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Ivy','in@sitametluctus.co.uk','Brennan',43,39,49,'accumsan convallis, ante lectus');
INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Hoyt','sed.consequat@odioapurus.edu','Ulysses',40,37,48,'Cras convallis convallis dolor.');
INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Anne','lobortis.quam@sedleo.com','Clayton',43,40,48,'mauris eu elit. Nulla');
INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Keaton','Cras.dictum@sapienimperdiet.net','Myles',41,35,37,'auctor. Mauris vel turpis.');
INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Ethan','ac.mattis.ornare@purusMaecenaslibero.org','Dillon',45,35,43,'ligula. Donec luctus aliquet');
INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Lee','ultrices.Vivamus@nullaIntincidunt.edu','Hoyt',43,40,35,'non, hendrerit id, ante.');
INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Walker','risus.Duis@ametnullaDonec.edu','Keith',36,39,43,'quam, elementum at, egestas');
INSERT INTO PARTICIPANTE (NOME,EMAIL,SENHA,TAMANHOCALCA,TAMANHOCAMISA,TAMANHOSAPATO,INTERESSES) VALUES ('Boris','convallis.convallis@arcuSedeu.co.uk','Camden',46,40,43,'odio, auctor vitae, aliquet');




CREATE TABLE EVENTO (
    EVENTOCOD INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    EVENTONOME VARCHAR(255),
    DATASORTEIO date,
    DATAEVENTO date,
    SITUACAO INTEGER,
    SENHAEVENTO VARCHAR(255),
    PRIMARY KEY (EVENTOCOD)
);
               



INSERT INTO EVENTO (EVENTONOME,DATASORTEIO,DATAEVENTO,SITUACAO,SENHAEVENTO) VALUES ('imperdiet ullamcorper.','2018-05-08','2018-07-15',0,'1234');
INSERT INTO EVENTO (EVENTONOME,DATASORTEIO,DATAEVENTO,SITUACAO,SENHAEVENTO) VALUES ('ipsum.','2018-06-07','2018-10-09',0,'1234');
INSERT INTO EVENTO (EVENTONOME,DATASORTEIO,DATAEVENTO,SITUACAO,SENHAEVENTO) VALUES ('nec,','2018-01-07','2018-11-07',0,'1234');
INSERT INTO EVENTO (EVENTONOME,DATASORTEIO,DATAEVENTO,SITUACAO,SENHAEVENTO) VALUES ('eu sem.','2018-09-07','2018-12-12',0,'1234');
INSERT INTO EVENTO (EVENTONOME,DATASORTEIO,DATAEVENTO,SITUACAO,SENHAEVENTO) VALUES ('ac,','2018-06-07','2018-10-07',0,'1234');
INSERT INTO EVENTO (EVENTONOME,DATASORTEIO,DATAEVENTO,SITUACAO,SENHAEVENTO) VALUES ('amet, consectetuer','2018-10-13','2018-06-07',0,'1234');
INSERT INTO EVENTO (EVENTONOME,DATASORTEIO,DATAEVENTO,SITUACAO,SENHAEVENTO) VALUES ('erat vitae','2018-05-07','2018-08-07',0,'1234');
INSERT INTO EVENTO (EVENTONOME,DATASORTEIO,DATAEVENTO,SITUACAO,SENHAEVENTO) VALUES ('sit','2018-01-07','2018-10-07',0,'1234');
INSERT INTO EVENTO (EVENTONOME,DATASORTEIO,DATAEVENTO,SITUACAO,SENHAEVENTO) VALUES ('nisi.','2018-09-07','2018-12-07',0,'1234');

CREATE TABLE atividade (
    atvcod INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ,
    PARTICIPANTECOD INTEGER NOT NULL ,
    eventocod INTEGER NOT NULL ,
    sorteado integer,
    PRIMARY KEY (atvcod),
    FOREIGN KEY (eventocod) REFERENCES Evento(eventocod),
    FOREIGN KEY (PARTICIPANTECOD) REFERENCES PARTICIPANTE(PARTICIPANTECOD)
    
);





INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (1,1,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (2,1,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (3,1,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (4,1,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (7,2,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (8,2,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (10,2,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (4,2,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (5,2,NULL);

INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (1,3,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (2,3,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (3,3,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (4,3,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (7,3,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (8,3,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (9,3,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (11,3,NULL);
INSERT INTO ATIVIDADE (PARTICIPANTECOD,EVENTOCOD,SORTEADO) VALUES (10,3,NULL);